### ISSUE TITLE
Enable students to view grades

### ISSUE THREAD

**Issue by agentry5** [agentry5/github-flow-exercise#1]
**PBI**:
Student-user view of grade changes made to courses by Instructor-users. 

**More description, planning**:
Students are only capable of viewing grades and grade-changes made for courses/assignments they are permitted to viewing by Administrators. Only instructors have the capability of changing grades, so students should not have any grade-altering functionality outside of "what-if" scores: when a student is viewing grades, they should be able to alter a score to see how it would affect their final grade in that course, with that altered score only appearing on the student-user's frontend view as a "what-if" score and is not saved in the course's grade database. There should be an appropriate HTML view for student's grades in all courses, as well as an HTML view that expands a course into the individual grades obtained for assignments within a course. Javascript should be used to calculate "what-if" scores' impact on course grade by utilizing an assignment's weight value assigned by Instructors.

**User story**:
As a student, I'd like to be able to view changes to my grades after teachers update them. If my teacher does not return physically/digitally submitted homework with scores written on them, how will I know how I performed on that assignment?

* Persona: Student attending a course
* Feature: Student view of grades for assignments/courses
* Business value: Students will be able to automatically view scores without relying on teacher to return submitted work.

**Task List**:
- [ ] Make sure appropriate databases are viewable to student profile
- [ ] Create HTML view for course-grades list
- [ ] Create HTML view for expanded assignment-grades list when a course grade is clicked
- [ ] Allow for front-end functionality of "what-if" scores

**Acceptance criteria**:
1. Only works for current semester
2. Students can only view grades for courses they are attending
3. Only works on Chrome browser

**Acceptance tests**:
1. Student should be able to view calculated cumulative scores for all courses.
2. Student should be able to view grades for individual assignments.
3. Student should be able to click an assignment score to redirect to assignment's page.
4. Student should be able to enter "what-if" values in assignment scores to see how they affect cumulative score. These entered values are not saved as actual scores.
